#!/usr/bin/env bash

echo "This script may need to be executed with 'sudo'."

uname=$(uname)
if [ $uname = "Darwin" ]; then
   brew install clojure
elif [ $uname = "Linux" ]; then
   clj_revision=1.9.0.391
   curl -O https://download.clojure.org/install/linux-install-${clj_revision}.sh
   chmod +x linux-install-${clj_revision}.sh
   ./linux-install-${clj_revision}.sh
fi
