#!/usr/bin/env bash

source $(dirname $0)/validate-kafka-env

if [ "$kafka_home" ]; then
   cd ${kafka_home}
   if [ $# -eq 1 ]; then
      topic=$1
   else
      echo "Missing topic name!"
      exit 1
   fi

   if [ ${BOOTSTRAP_SERVERS} ]; then
      ./bin/kafka-console-consumer.sh --bootstrap-server ${BOOTSTRAP_SERVERS} --topic ${topic} --from-beginning | jq . -C -
   else
      ./bin/kafka-console-consumer.sh --zookeeper ${ZK_HOSTS} --topic ${topic} --from-beginning | jq . -C -M -
   fi    
fi

# vim: ft=sh
