#!/usr/bin/env bash

source etc/utils.shlib

# If this script is sourced skip the rest and return
[ "$0" = "$BASH_SOURCE" ] && v=run || return 0;

# override maven output directory 'target' & gradle ouput directory 'build/libs'
OUT_DIR=deploy
set_revision

jdk_ops='-J-XX:+IgnoreUnrecognizedVMOptions -J--add-modules=java.xml.bind,java.xml.ws'

function run_cmd() {
   repl=-J-Dclojure.server.repl="{:port ${REPL_PORT} :accept clojure.core.server/repl}"
   nrepl="-J-Dnrepl.port=${NREPL_PORT}"
   aliases=:dev:test
   if [ "$1" == "jar" ]; then
      if [ -f ${FQ_APP} ]; then
         java -jar ${FQ_APP}
      else
         ./run pkg
         ./run dev jar
      fi
   elif [ "$1" == "itest" ]; then
     # In a shell 'run dev jar' & in another shell 'run itest' to interactively test drive the jar with vim.
     clj $jdk_ops "$repl" $nrepl -R$aliases -C$aliases -i src/dev/clj/init-cider.clj -m msa.core-test
   elif [ "$1" == "repl" ]; then
     # will include $CP/user.clj automatically
     clj $jdk_ops "$repl" $nrepl -A$aliases -i src/dev/clj/init-cider.clj -r
   elif [ "$1" == "nrepl" ]; then
     # will include $CP/user.clj automatically. https://nrepl.readthedocs.io/en/latest/usage
     clj $jdk_ops "$repl" $nrepl -A$aliases -i src/dev/clj/init-cider.clj -m nrepl.cmdline --interactive --color
   elif [ "$1" == "rebl" ]; then
     # use clojure since clj uses rlwrap. rebel-readline does not include $CP/user.clj.
     # Use -i explicitly but be sure to use (ns user) in -i script. Cannot use clojure "slim" classifier.
     clojure $jdk_ops "$repl" $nrepl -A$aliases -i src/dev/clj/init-cider.clj -i src/dev/clj/user.clj -m rebel-readline.main
   elif [ "$1" == "depstar" ]; then
      clj -Scp ${FQ_DS_APP} -m msa.core
   elif [ "$1" == "capsule" ]; then
      java -jar ${FQ_CAPS_APP}
   elif [ "$1" == "1jar" ]; then
      java -jar ${FQ_1JAR_APP} -m msa.core
   else
     # will include $CP/user.clj automatically
     clj $jdk_ops "$repl" $nrepl -R$aliases -C$aliases -i src/dev/clj/init-cider.clj -m msa.core
   fi
}

if [ "$1" == "host" ]; then
   # See docker --env HOST_IP="a.b.c.d"
   source bin/set-kafka-cluster host $2
   bin/validate-kafka-env
   run_cmd $3
elif [ "$1" == "dev" ]; then
   jenv graal; java -version
   set_repl_ports
   source bin/set-kafka-cluster local
   bin/validate-kafka-env
   # Debug interactively against a production configuration. Check config.edn.
   #export CONFIG_PROFILE=':prod'; export TIMBRE_LEVEL=':debug'
   export RUN_DEV_MODE=true
   run_cmd $2
elif [ "$1" == "prod" ]; then
   source bin/set-kafka-cluster hop
   bin/validate-kafka-env
   export CONFIG_PROFILE=':prod'
   # Debug interactively against a production environment.
   #export RUN_DEV_MODE=true; export TIMBRE_LEVEL=':debug'
   run_cmd $2
elif [ "$1" == "pkg" ]; then
   jenv graal; java -version
   # Remove dependencies on development jars
   touch deps.edn
   clojure -Sverbose -Spom $*
   [ -d deploy ] || mkdir deploy
   if [ "$2" == "mvn" ]; then
      # 'auto merge' mvn plugins into the generated pom.xml. Only add clojure-maven-plugin xml when not present in pom.xml
      grep -q '^[ \t]*<artifactId>clojure-maven-plugin</artifactId>' pom.xml || sed -i -e '/<sourceDirectory>src\/main\/clj<\/sourceDirectory>/r src/dev/mvn-plug-res.xml' pom.xml
      [ -f pom.xml ] && rm pom.xml-e
      mvn package
   elif [ "$2" == "depstar" ]; then
      FQ_APP=${FQ_DS_APP}
      clj -A:depstar -m hf.depstar.uberjar ${FQ_APP}
   elif [ "$2" == "capsule" ]; then
      FQ_APP=${FQ_CAPS_APP}
      clj -A:pack mach.pack.alpha.capsule -m msa.core --application-id $APP --application-version $REVISION \
         -M "Built-By: $USER" -M "Build-Timestamp: $(date)" -M "Build-Host: $(uname -vn)" \
         ${FQ_APP}
   elif [ "$2" == "1jar" ]; then
      FQ_APP=${FQ_1JAR_APP}
      clj -A:pack mach.pack.alpha.one-jar ${FQ_APP}
   elif [ "$2" == "gradle" ]; then
      # run gradle with the JDK selected by this script.
      gradle -Dorg.gradle.java.home=$JAVA_HOME shadowJar
   else
      bin/pkg
   fi
   gen_proj_pom
   tar -cf `sed s/.jar$/.tar/g <<<${FQ_APP}` bin run ${FQ_APP_NS}.pom ${FQ_APP}
elif [ "$1" == "docker" ]; then
   if [ "$2" == "run" ]; then
      if [ ! $DOCKER_ENV_FILE ] ;then
         echo "Please set DOCKER_ENV_FILE environment variable before invoking \"./run docker run\" command."
         echo "  e.g.: export DOCKER_ENV_FILE=~/.secrets (chmod go-rwx)"
         exit -1
      fi
      docker stop ${APP}
      docker rm ${APP}
      docker run --env-file ${DOCKER_ENV_FILE} -d --name ${APP} ${APP}:${REVISION}
      ./run docker ls
   elif [ "$2" == "debug" ]; then
      if [ ! $DOCKER_ENV_FILE ] ;then
         echo "Please set DOCKER_ENV_FILE environment variable before invoking \"./run docker debug\" command."
         echo "  e.g.: export DOCKER_ENV_FILE=~/.secrets (chmod go-rwx)"
         exit -1
      fi
      docker stop ${APP}
      docker rm ${APP}
      docker run --env-file ${DOCKER_ENV_FILE} -d -t -i --entrypoint /bin/sh --name ${APP} ${APP}:${REVISION}
      ./run docker ls
      # after 'run docker debug' completes, run 'docker attach some-id'
   elif [ "$2" == "ls" ]; then
      echo "Containers..."
      docker ps -a --filter name=${APP}
      echo ""
      echo "Images..."
      docker images | grep ${APP}
   elif [ "$2" == "clean" ]; then
      docker rm $(docker ps -aq --filter name=${APP})
      docker rmi $(docker images | grep ${APP} | awk "{print \$3}")
      ./run docker ls
   elif [ "$2" == "scrub" ]; then
      ./run docker clean
      docker rmi $(docker images | grep '<none>' | awk "{print \$3}")
      docker images
   elif [ "$#" -eq 1  ]; then
      ./run pkg
      # ./run pkg above may change $REVISION, be sure to pick that up.
      get_revision
      docker build -t ${APP}:${REVISION} .
   else
      ./run usage
   fi
elif [ "$1" == "clean" ]; then
   rm -rf $(cat etc/generated-artifacts | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/ /g')
else
   echo "Usage:"
   echo "   run clean"
   echo "   [nohup] run host ip|dev|prod [repl|nrepl|rebl|itest|jar|depstar|capsule|1jar] [&]"
   echo "   run pkg [mvn|gradle|depstar|capsule|1jar]"
   echo "   run docker [run|debug|clean|ls|scrub]"
fi
